apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::800762100828:role/service-role/codebuild-WebAppProject-service-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::800762100828:role/service-role/codebuild-WebAppProject-service-role
      username: build
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::800762100828:user/mamta
      username: mamta
      groups:
        - system:masters



kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system